# Exercise 32-02 v1.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client01-deploy
  namespace: dev-ns
  labels:
    app: store-app
    tier: client
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: client01-pod
  template:
    metadata:
      labels:
        pod: client01-pod
    spec:
      containers:
      - name: client-app
        image: alpine:latest
        command:
        - sleep
        - "3600"
---
apiVersion: v1
kind: Service
metadata:
  name: client01-svc
  namespace: dev-ns
  labels:
    app: store-app
spec:
  type: ClusterIP
  selector:
    pod: client01-pod
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
