# Exercise 32-02 v1.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01
  namespace: dev-ns
  labels:
    app: store-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: web01-pod
  template:
    metadata:
      labels:
        pod: web01-pod
    spec:
      containers:
      - name: kube-backend
        image: wmdailey/kube-backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: web01-svc
  namespace: dev-ns
  labels:
    app: store-app
spec:
  type: ClusterIP
  selector:
    pod: web01-pod
  ports:
    - name: http
      port: 5000 
      targetPort: 5000 
      protocol: TCP
