# Exercise 04-06 v1.0.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app02-pod
  namespace: default
  labels:
    bu: dev
    env: dev
    tier: mid
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "4800"
