# Exercise 28-03 v1.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app01-pod 
  namespace: prd-ns 
  labels:
    tier: frontend
spec:
  containers:
    - name: frontend
      image: wmdailey/edu-backend 
      ports:
         - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prd-ns
  labels:
    tier: frontend
spec:
  type: ClusterIP 
  selector:
    pod: app01-pod
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000
