# Exercise 06-05 v1.0.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: db01-pod
  namespace: default
  labels:
    bu: fin
    env: stage
    tier: db
spec:
  containers:
  - name: db-app
    image: redis:latest
