apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/wdailey/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 08 Jul 2025 20:24:53 PDT
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: cluster_info
    server: https://127.0.0.1:60916
  name: devl
contexts:
- context:
    cluster: kind-prd01
    namespace: default
    user: bo_biz
  name: bo_biz@kind-prd01
- context:
    cluster: devl
    extensions:
    - extension:
        last-update: Tue, 08 Jul 2025 20:24:53 PDT
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: context_info
    namespace: default
    user: dana_dev
  name: dana_dev@devl
current-context: dana_dev@devl
kind: Config
preferences: {}
users:
- name: dana_dev
  user:
    password: u8BQdkUl9l35qcif
    username: dana_dev
