# Exercise 04-06 v1.0.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: db02-pod
  namespace: default
  labels:
    bu: fin
    env: test
    tier: db
spec:
  containers:
  - name: db-app
    image: redis
