apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-backend 
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: edu-backend 
  template:
    metadata:
      labels:
        name: edu-backend 
    spec:
      containers:
      - name: edu-backend 
        image: wmdailey/edu-backend:latest
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 5000

