# Exercise 28-02 v1.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app01-pod 
  namespace: db-ns 
  labels:
    tier: frontend
    app: store-app
spec:
  containers:
    - name: node
      image: wmdailey/kube-backend 
      ports:
         - containerPort: 5000 
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: db-ns
  labels:
    app: store-app
spec:
  type: ClusterIP 
  selector:
    pod: app01-pod
  ports:
    - protocol: TCP
      port: 5000 
      targetPort: 5000
