# Exercise 28-02 v1.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app01-pod 
  namespace: db-ns 
spec:
  containers:
    - name: node
#       image: wdailey/node-app
       image: csanchez/croc-hunter 
#      image: node:21-alpine
#      command: ['sh', '-c', "tail -f /dev/null"]
      ports:
         - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: db-ns
  labels:
    app: store-app
spec:
  type: ClusterIP 
  selector:
    pod: app01-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
