apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: db10-netpold01
spec:
  podSelector:
    matchLabels:
      name: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: db10-pod
    ports:
    - port: 3306