# Exercise 17-02 v1.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app02-pod 
  template:
    metadata:
      labels:
        pod: app02-pod 
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        command: ["sh", "-c", "echo Hello Cloudera Edu! && sleep 3600"] 
        env:
          - name: END_USER
            valueFrom:
              configMapKeyRef:
                name: app02-a-cm
                key: END_USER
          - name: GROUPS 
            valueFrom:
              configMapKeyRef:
                name: app02-a-cm
                key: GROUPS 
          - name: ROLE 
            valueFrom:
              configMapKeyRef:
                name: app02-b-cm
                key: ROLE 
          - name: QOP 
            valueFrom:
              configMapKeyRef:
                name: app02-b-cm
                key: QOP 
          - name: STAT.INTERVAL 
            valueFrom:
              configMapKeyRef:
                name: app02-b-cm
                key: STAT.INTERVAL 
          - name: CHANNEL_ADDRESS 
            valueFrom:
              configMapKeyRef:
                name: app02-b-cm
                key: CHANNEL_ADDRESS 
          - name: REDUNANCY 
            valueFrom:
              configMapKeyRef:
                name: app02-b-cm
                key: REDUNANCY 
        resources: {}
