# Exercise 17-02 v1.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app03-pod 
  template:
    metadata:
      labels:
        pod: app03-pod 
    spec:
      containers:
      - name: busy-app 
        image: busybox:1.28
        command: ["sh", "-c", "ls /etc/config/ && sleep 360"] 
        volumeMounts:
          - name: app03-cm-vol
            mountPath: /etc/config
        resources: {}
      volumes:
        - name: app03-cm-vol
          configMap:
            name: app03-cm


            
