# Exercise 28-02 v1.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: app01-pod 
  namespace: dev-ns
  labels:
    app: store-app
    tier: frontend
spec:
  containers:
    - name: store-app
      image: busybox:latest 
      command: ["/bin/sh", "-c", "while true; do echo '' | nc -l -p 3000; done"]
      ports:
        - containerPort: 3000
      resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: dev-ns
  labels:
    app: store-app
    tier: frontend
spec:
  type: ClusterIP 
  selector:
    pod: app01-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
