# Exercise 09-05 v1.3.0
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db01-cm 
  namespace: dev-ns
  labels:
    app: db01-db 
data:
  POSTGRES_DB: db01-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: BadPass@1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db01-sts
  namespace: dev-ns
  labels:
    app: db01-db
spec:
  serviceName: db01-svc
  selector:
    matchLabels:
      pod: db01-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: db01-pod
    spec:
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "db"
          effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db01-cm 
---
apiVersion: v1
kind: Service
metadata:
  name: db01-svc
  namespace: dev-ns
  labels:
    app: db01-db
spec:
  selector:
    pod: db01-pod
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
