apiVersion: v1
clusters:
- cluster:
    server: ""
  name: ""
- cluster:
    certificate-authority: /Users/wdailey/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 25 Apr 2025 11:28:02 +03
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: cluster_info
    server: https://127.0.0.1:50805
  name: mini01
contexts:
- context:
    cluster: mini01
    extensions:
    - extension:
        last-update: Fri, 25 Apr 2025 11:28:02 +03
        provider: minikube.sigs.k8s.io
        version: v1.35.0
      name: context_info
    namespace: default
    user: mini01
  name: mini01
current-context: dana_dev@mini01
kind: Config
preferences: {}
users:
- name: dana_dev
  user:
    password: u8BQdkUl9l35qcif
    username: dana_dev
